[package]
name = "kenja"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
prost = "0.13.5"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.12.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[build-dependencies]
tonic-build = "0.12.3"
